# https://github.com/ruslanmv/How-to-build-Docker-Images-with-GitHub

name: Build and push docker image to Azure docker reg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Generate timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag powergydockerreg.azurecr.io/mcp-server:latest

    - name: Push the Docker image
      run: docker push powergydockerreg.azurecr.io/mcp-server:latest